INSERT INTO PERSON(EMAIL, NAME, AGE) VALUES ('kydann@gmail.com','CHRISTIAN',25)
INSERT INTO PERSON(EMAIL, NAME, AGE) VALUES ('diana@gmail.com','DIANA',17)
INSERT INTO PERSON(EMAIL, NAME, AGE) VALUES ('erick@gmail.com','ERICK',22)